### ISSUE TITLE
Jobs scheduled using `RedisStorage::schedule` are not running at all

### ISSUE THREAD

**Issue by ChristianIvicevic** [geofmureithi/apalis#50]
I started exploring this crate and attempted the following:
```rust
use std::ops::Add;

use apalis::{layers::Extension, prelude::*, redis::RedisStorage};
use chrono::{Duration, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
struct Event {
    id: u64,
}

impl Job for Event {
    const NAME: &'static str = "test::Event";
}

async fn produce_jobs(mut storage: RedisStorage<Event>) -> anyhow::Result<()> {
    for index in 0..5 {
        tracing::info!("Scheduling event: {}", index);
        let time = Utc::now().add(Duration::seconds((2 * (index + 1)) as i64));
        storage.schedule(Event { id: index }, time).await?
    }
    Ok(())
}

async fn handle_event(job: Event, _ctx: JobContext) -> Result<JobResult, JobError> {
    tracing::info!("Handling event: {:?}", job);
    Ok(JobResult::Success)
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt::init();

    let storage = RedisStorage::connect("redis://127.0.0.1/").await?;

    let storage_clone = storage.clone();
    let _ = tokio::spawn(async move {
        tokio::time::sleep(tokio::time::Duration::from_secs(3)).await;
        produce_jobs(storage_clone).await.ok();
    });

    Monitor::new()
        .register(
            WorkerBuilder::new(storage.clone())
                .layer(Extension(storage.clone()))
                .build_fn(handle_event),
        )
        .run()
        .await
}
```

The events queued after the app is started do not get handled at all. Restarting the application does handle them retroactively though. I was expecting that after 3 seconds one queued event would be handled every 2 seconds. Is there something I am missing here?

**Comment by geofmureithi** [comment]
Hmm this is an interesting problem. I will try to replicate and look at what is happening.

**Comment by ChristianIvicevic** [comment]
Here's some additional data on what I am using:
- Redis: `bitnami/redis:7.0.9`
- Rust: `nightly-2022-11-04`
- OS: macOS 13.2.1 ARM
- Cargo dependencies:
```toml
anyhow = "1.0.69"
apalis = { version = "0.3.6", features = ["redis", "extensions"] }
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
dotenvy = "0.15.6"
serde = "1.0.152"
tokio = { version = "1.25.0", features = ["macros"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
```
