### ISSUE TITLE
`PostgresStorage::list_jobs()` returns `argument of OFFSET must be type bigint, not type text` error

### ISSUE THREAD

**Issue by twistedfall** [geofmureithi/apalis#528]
Hi,

When trying to call the `list_jobs()`on the `PostgresStorage` backend in the latest Apalis (0.6.4) I'm getting the following error:
```
PgDatabaseError {
severity: Error,
code: "42804",
message: "argument of OFFSET must be type bigint, not type text",
detail: None,
hint: None,
position: Some(Original(114)),
where: None,
schema: None,
table: None,
column: None,
data_type: None,
constraint: None,
file: Some("parse_coerce.c"),
line: Some(1221),
routine: Some("coerce_to_specific_type_typmod")
}
```
Looks like it's because the `bind()` argument is converted to string:
```rust
            .bind(((page - 1) * 10).to_string())
```
I'm running Postgres version 13.

Additionally the `page` argument for the first page is expected to be `1` which is something I think worth mentioning in the docs for the `list_jobs()` method.

Thank you for your work on the crate!

**Comment by geofmureithi** [comment]
I think this was fixed in in this [PR](https://github.com/geofmureithi/apalis/pull/524/files#diff-8872415982569969c3b3a0fa114d9c309c461b70fbd8c8994ac15990d1b02a8cR747)

**Comment by geofmureithi** [comment]
Please try with the latest main.

**Comment by jpoisso** [comment]
Hi @geofmureithi ,  I'm not the OP but I had the same problem after migrating to Postgres from Redis.

```toml
apalis = { git = "https://github.com/geofmureithi/apalis.git", features = ["tracing", "timeout", "limit", "retry", "prometheus", "uuid", "layers"], default-features = false}
apalis-sql = { git = "https://github.com/geofmureithi/apalis.git", features = ["tokio-comp", "postgres", "migrate"], default-features = false}
```

That PR does appear to resolve the issue, thank you!

PS: for some reason with redis, I used page = 0 succesfully but I had to change it to 1 for apallis-sql.
